# Generated by Django 5.1.4 on 2024-12-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dumapp', '0003_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='price',
        ),
    ]
